name: Deploy a GitHub Pages

on:
  push:
    branches: [master] # Cambia 'main' si tu rama principal se llama 'master'

permissions:
  contents: write # Necesario para que el action pueda escribir en la rama gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar el proyecto (Build)
        run: npm run build

      - name: Desplegar a la rama gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Astro genera la web en esta carpeta
          publish_branch: gh-pages # El nombre de la rama donde se guardará la web
